//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AARCO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Marcas
    {
        public Marcas()
        {
            this.Submarcas = new HashSet<Submarcas>();
        }
    
        public int id { get; set; }
        [Required]
        public string Marca1 { get; set; }
    
        public virtual ICollection<Submarcas> Submarcas { get; set; }
    }
}
