//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AARCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submarcas
    {
        public Submarcas()
        {
            this.Modelo = new HashSet<Modelo>();
        }
    
        public int id { get; set; }
        public string Submarca { get; set; }
        public int idMarca { get; set; }
    
        public virtual Marcas Marcas { get; set; }
        public virtual ICollection<Modelo> Modelo { get; set; }
    }
}
